server.port=${SERVER_PORT:8012}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:8004/lavernedb}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

security.jwt.secret-key=${JWT_SECRET_KEY}
admin.default.username=${ADMIN_USERNAME:admin}
admin.default.password=${ADMIN_PASSWORD}
