server.port=${SERVER_PORT:8088}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:8007/lavernedb}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

security.jwt.secret-key=${JWT_SECRET_KEY}
admin.default.username=${ADMIN_USERNAME:admin}
admin.default.password=${ADMIN_PASSWORD}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:8089}
