server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/lavernedb
spring.datasource.username=postgres
spring.datasource.password=admin

security.jwt.secret-key=652YH24A66556A586E3272357538782PJ536Z8B8472B4B6250645367635O8TH5
